### ISSUE TITLE
Connection issues using Earth Data login

### ISSUE THREAD

**Issue by jfprieur** [icesat2py/icepyx#217]
Hello, I am getting this error after submitting my logon credentials via the console and trying to download ATL08 data.

According to the comments in earthdata.py, the .netrc file should only be looked up if manual credentials are not provided (they were provided in this case).

This is using miniconda (Python 3.8.6) on Windows 10 

```
Earthdata Login password: xxxxxxxxx
Traceback (most recent call last):

  File "C:\ProgramData\Miniforge3\envs\geopandas\lib\site-packages\icepyx\core\Earthdata.py", line 121, in login
    self.uid, _, self.pswd = netrc.netrc(self.netrc).authenticators(url)

  File "C:\ProgramData\Miniforge3\envs\geopandas\lib\netrc.py", line 29, in __init__
    with open(file) as fp:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxxxx\\.netrc'
```

If I supply a .netrc file, it ignored it and still asks me for my credentials. I then get (again, I can log in OK on the Earth Data website with the same credentials)

```
Earthdata Login password: xxxxxxxxx
Traceback (most recent call last):

  File "C:\ProgramData\Miniforge3\envs\geopandas\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(

  File "C:\ProgramData\Miniforge3\envs\geopandas\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err

  File "C:\ProgramData\Miniforge3\envs\geopandas\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

How do I continue to troubleshoot?

**Comment by jfprieur** [comment]
Should always check the status alerts, LP DAAC and HTTP downloads unavailable today

**Comment by JessicaS11** [comment]
Good catch and glad you figured it out - let us know if you keep having issues once the site is back up an running!
