### ISSUE TITLE
Connection Error to Earth Data login

### ISSUE THREAD

**Issue by nitin-ravinder** [icesat2py/icepyx#274]
```
import icepyx as ip
import os
import shutil

# Parameters to create a Query object for our data search
uid = 'user_name'
email = 'email@email.com'
data_path = 'path to data'
short_name = 'ATL06'
reg_a_bbox = [-55, 68, -48, 71]
reg_a_dates = ['2019-02-20','2019-02-28']
cycles = ['03', '04', '05', '06', '07']
tracks=['0849','0902']
reg_a = ip.Query(short_name, reg_a_bbox, cycles=cycles, tracks=tracks)

reg_a.earthdata_login(uid,email)
```
When I try to query some files to download using the code above, I get the following error.
```
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```
Sometimes, I am able to login without the error above. But, running the following line of code, I get the server error below.
```
reg_a.order_granules()
```
```
Traceback (most recent call last):

  File "/tmp/ipykernel_6114/2647441721.py", line 5, in <module>
    reg_a.order_granules()

  File "/home/ravnit/anaconda3/envs/icepyx-env/lib/python3.10/site-packages/icepyx/core/query.py", line 884, in order_granules
    self._granules.place_order(

  File "/home/ravnit/anaconda3/envs/icepyx-env/lib/python3.10/site-packages/icepyx/core/granules.py", line 352, in place_order
    request.raise_for_status()

  File "/home/ravnit/anaconda3/envs/icepyx-env/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 501 Server Error: Not Implemented for url: https://n5eil02u.ecs.nsidc.org/egi/request?short_name=ATL06&version=005&options%5Breadable_granule_name%5D%5Bpattern%5D=true&options%5Bspatial%5D%5Bor%5D=true&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084903%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090203%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084904%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090204%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084905%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090205%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084906%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090206%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_084907%3F%3F_%2A&readable_granule_name%5B%5D=ATL06_%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F_090207%3F%3F_%2A&bounding_box=-55.0%2C68.0%2C-48.0%2C71.0&page_size=2000&page_num=1&request_mode=async&include_meta=Y&client_string=icepyx&bbox=-55.0%2C68.0%2C-48.0%2C71.0

sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f2c2505f100>
```

**Comment by JessicaS11** [comment]
@weiji14 Thanks for working with @nitin-ravinder on this (and thanks for reporting the issue). Have you done any more digging into the error or been able to reproduce it?

**Comment by weiji14** [comment]
No I haven't tried to reproduce the connection error yet. I gave a suggestion to downgrade to Python 3.9 (because there have been some weird issues with some libraries on Python 3.10) but not sure if that actually worked. Nitin did mention yesterday that he was also having issues with accessing the NSIDC data URL directly too, so I was wondering if there might be some problem on the NSIDC server.

**Comment by nitin-ravinder** [comment]
Thanks @JessicaS11 and @weiji14 for following up on the issue. I tried again by downgrading to Python 3.9 as suggested by Wei Ji, I ran into the same issues. The Connection error while logging in did not appear after I ran the line again and entered the password for login. Essentially, I am still facing the same issues (Another error while reading data, when I try to 'load' onto a variable, the Kernel just restarts - I'm using Spyder). Perhaps, there's something wrong with the installation itself. I used conda to install. I also tried pip installation and with that, I got a different error when reading and loading data (no kernel restart) although the connection error was still the same. I will try pip installation with Python 3.9 and check how it goes.

**Comment by nitin-ravinder** [comment]
Hi @JessicaS11  and @weiji14, apologies for taking a long time in getting back on this. I tried pip installation with Python 3.9. The connection error doesn't seem to be an issue anymore. But when I order granules, I still get the HTTP Error. At this point, I wouldn't want to download the data through the code anyway, because it is a lot of files. The issue I previously faced while reading the data is also gone. So, I think it is working better with Python 3.9 for me. If it is okay with you, I can go ahead and close this issue.

**Comment by nitin-ravinder** [comment]
Yes, I'm still getting that error, even after the downgrading python.

And, yes, I received a decision regarding my application (although, it was not accepted :( ). But, I'll looked forward to the videos and tutorials.

**Comment by JessicaS11** [comment]
I'm going to close this issue and open a new one to handle the HTTP error (which I was able to reproduce), since it not longer seems to be about the Earthdata login.
