### ISSUE TITLE
region_a.order_vars.avail() : Error occurs while searching available variables ATL10 

### ISSUE THREAD

**Issue by marionbocquet** [icesat2py/icepyx#637]
```python
region_a = ipx.Query('ATL10',[-55, 50, 48, 71],['2019-02-22','2019-02-28'], start_time='00:00:00', end_time='23:59:59')
region_a.order_vars.avail()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packages/icepyx/venv/icepyx/lib/python3.9/site-packages/icepyx/core/variables.py", line 142, in avail
    self._avail = is2ref._get_custom_options(
  File "packages/icepyx/venv/icepyx/lib/python3.9/site-packages/icepyx/core/is2ref.py", line 116, in _get_custom_options
    format_vals.remove("")
ValueError: list.remove(x): x not in list
```

**Same as for region_a.order_vars**

**Comment by mfisher87** [comment]
I did a quick edit to format your code. Here's how I did it:

``````
```python
region_a = ipx.Query('ATL10',[-55, 50, 48, 71],['2019-02-22','2019-02-28'], start_time='00:00:00', end_time='23:59:59')
region_a.order_vars.avail()
```
``````

I'm able to reproduce this on my end.

**Comment by JessicaS11** [comment]
Thanks for reporting, @marionbocquet and confirming it's a bug @mfisher87, and your patience through AGU and the holiday season for us to get to this in more detail.

It turns out that there is a current, known issue with the CMR metadata for ATL10 that is currently being worked on by NSIDC/ICESat-2 data production. In the `ipx.Query` use case shown here, the variables information is pulled from these metadata files, so I suspect that's the source of this issue.

That said, we also have some ongoing development that will impact the `region_a.order_vars` functionality that may influence how you want to update your workflow. You can still use [the Variables module](https://icepyx.readthedocs.io/en/latest/example_notebooks/IS2_data_variables.html) via `ipx.Read` or on its own, but it will soon stop working as part of a data download workflow.  NSIDC (where icepyx gets ICESat-2 data from) is currently changing over their backend and therefore what services will be available. Variable subsetting will no longer be available when ordering data. If you use the icepyx Read module, you can selectively open only your desired variables, and we are working on making it easy for users to only access the variables they need in the cloud.

Given all this, I am going to close this issue as "not planned" because it is the result of a non-icepyx issue and applies to code and services that are planned to be deprecated. However, please feel free to comment here or reach out if we can help in any way. Our goal is to make the transition as painless to users as possible (so invisible in using icepyx wherever possible, yet 100% transparent wherever changes are required).
